/**
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 2.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class JsonAtlasGlossaryTerm (
  // 
  guid: Option[String] = None,
  // 
  classifications: Option[List[JsonAtlasClassification]] = None,
  // 
  longDescription: Option[String] = None,
  // 
  name: Option[String] = None,
  // 
  qualifiedName: Option[String] = None,
  // 
  shortDescription: Option[String] = None,
  // 
  abbreviation: Option[String] = None,
  anchor: Option[JsonAtlasGlossaryHeader] = None,
  // 
  antonyms: Option[List[JsonAtlasRelatedTermHeader]] = None,
  // 
  assignedEntities: Option[List[JsonAtlasRelatedObjectId]] = None,
  // 
  categories: Option[List[JsonAtlasTermCategorizationHeader]] = None,
  // 
  classifies: Option[List[JsonAtlasRelatedTermHeader]] = None,
  // 
  examples: Option[List[String]] = None,
  // 
  isA: Option[List[JsonAtlasRelatedTermHeader]] = None,
  // 
  preferredTerms: Option[List[JsonAtlasRelatedTermHeader]] = None,
  // 
  preferredToTerms: Option[List[JsonAtlasRelatedTermHeader]] = None,
  // 
  replacedBy: Option[List[JsonAtlasRelatedTermHeader]] = None,
  // 
  replacementTerms: Option[List[JsonAtlasRelatedTermHeader]] = None,
  // 
  seeAlso: Option[List[JsonAtlasRelatedTermHeader]] = None,
  // 
  synonyms: Option[List[JsonAtlasRelatedTermHeader]] = None,
  // 
  translatedTerms: Option[List[JsonAtlasRelatedTermHeader]] = None,
  // 
  translationTerms: Option[List[JsonAtlasRelatedTermHeader]] = None,
  // 
  usage: Option[String] = None,
  // 
  validValues: Option[List[JsonAtlasRelatedTermHeader]] = None,
  // 
  validValuesFor: Option[List[JsonAtlasRelatedTermHeader]] = None
)

