/**
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 2.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class JsonAtlasClassificationDef (
  category: Option[JsonTypeCategory] = None,
  // 
  createTime: Option[Number] = None,
  // 
  createdBy: Option[String] = None,
  dateFormatter: Option[JsonDateFormat] = None,
  // 
  description: Option[String] = None,
  // 
  guid: Option[String] = None,
  // 
  name: Option[String] = None,
  // 
  options: Option[Map[String, String]] = None,
  // 
  serviceType: Option[String] = None,
  // 
  typeVersion: Option[String] = None,
  // 
  updateTime: Option[Number] = None,
  // 
  updatedBy: Option[String] = None,
  // 
  version: Option[Number] = None,
  // 
  attributeDefs: Option[List[JsonAtlasAttributeDef]] = None,
  // Specifying a list of entityType names in the classificationDef, ensures that classifications can only be applied to those entityTypes.<ul><li>Any subtypes of the entity types inherit the restriction<li>Any classificationDef subtypes inherit the parents entityTypes restrictions<li>Any classificationDef subtypes can further restrict the parents entityTypes restrictions by specifying a subset of the entityTypes<li>An empty entityTypes list when there are no parent restrictions means there are no restrictions<li>An empty entityTypes list when there are parent restrictions means that the subtype picks up the parents restrictions<li>If a list of entityTypes are supplied, where one inherits from another, this will be rejected. This should encourage cleaner classificationsDefs<ul>
  entityTypes: Option[List[String]] = None,
  // 
  subTypes: Option[List[String]] = None,
  // 
  superTypes: Option[List[String]] = None
)

