/**
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 2.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class JsonAtlasEntityHeader (
  // 
  attributes: Option[Map[String, Any]] = None,
  // 
  typeName: Option[String] = None,
  // 
  classificationNames: Option[List[String]] = None,
  // 
  classifications: Option[List[JsonAtlasClassification]] = None,
  // 
  displayText: Option[String] = None,
  // 
  guid: Option[String] = None,
  // 
  meaningNames: Option[List[String]] = None,
  // 
  meanings: Option[List[JsonAtlasTermAssignmentHeader]] = None,
  status: Option[JsonStatus] = None
)

