/**
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 2.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class JsonAtlasRelationshipAttributeDef (
  cardinality: Option[JsonCardinality] = None,
  // 
  constraints: Option[List[JsonAtlasConstraintDef]] = None,
  // 
  defaultValue: Option[String] = None,
  // 
  description: Option[String] = None,
  // 
  includeInNotification: Option[Boolean] = None,
  // 
  isIndexable: Option[Boolean] = None,
  // 
  isOptional: Option[Boolean] = None,
  // 
  isUnique: Option[Boolean] = None,
  // 
  name: Option[String] = None,
  // 
  options: Option[Map[String, String]] = None,
  // 
  typeName: Option[String] = None,
  // 
  valuesMaxCount: Option[Integer] = None,
  // 
  valuesMinCount: Option[Integer] = None,
  // 
  isLegacyAttribute: Option[Boolean] = None,
  // 
  relationshipTypeName: Option[String] = None
)

