/**
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 2.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class JsonEntityAuditEventV2 (
  action: Option[JsonEntityAuditActionV2] = None,
  // 
  details: Option[String] = None,
  entity: Option[JsonAtlasEntity] = None,
  // 
  entityId: Option[String] = None,
  // 
  eventKey: Option[String] = None,
  // 
  timestamp: Option[Long] = None,
  `type`: Option[JsonEntityAuditType] = None,
  // 
  user: Option[String] = None
)

