/**
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 2.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class JsonNumberFormat (
  // 
  availableLocales: Option[List[String]] = None,
  // 
  currency: Option[String] = None,
  currencyInstance: Option[JsonNumberFormat] = None,
  // 
  groupingUsed: Option[Boolean] = None,
  instance: Option[JsonNumberFormat] = None,
  integerInstance: Option[JsonNumberFormat] = None,
  // 
  maximumFractionDigits: Option[Integer] = None,
  // 
  maximumIntegerDigits: Option[Integer] = None,
  // 
  minimumFractionDigits: Option[Integer] = None,
  // 
  minimumIntegerDigits: Option[Integer] = None,
  numberInstance: Option[JsonNumberFormat] = None,
  // 
  parseIntegerOnly: Option[Boolean] = None,
  percentInstance: Option[JsonNumberFormat] = None,
  roundingMode: Option[JsonRoundingMode] = None
)

