/**
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 2.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class JsonAtlasEntity (
  // 
  attributes: Option[Map[String, Any]] = None,
  // 
  typeName: Option[String] = None,
  // 
  classifications: Option[List[JsonAtlasClassification]] = None,
  // 
  createTime: Option[Number] = None,
  // 
  createdBy: Option[String] = None,
  // 
  guid: Option[String] = None,
  // 
  homeId: Option[String] = None,
  // 
  meanings: Option[List[JsonAtlasTermAssignmentHeader]] = None,
  // 
  provenanceType: Option[Number] = None,
  // 
  proxy: Option[Boolean] = None,
  // 
  relationshipAttributes: Option[Map[String, Any]] = None,
  status: Option[JsonStatus] = None,
  // 
  updateTime: Option[Number] = None,
  // 
  updatedBy: Option[String] = None,
  // 
  version: Option[Number] = None
)

