/**
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 2.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api

import java.text.SimpleDateFormat

import io.swagger.client.model.JsonAtlasLineageInfo
import io.swagger.client.{ApiInvoker, ApiException}

import com.sun.jersey.multipart.FormDataMultiPart
import com.sun.jersey.multipart.file.FileDataBodyPart

import javax.ws.rs.core.MediaType

import java.io.File
import java.util.Date
import java.util.TimeZone

import scala.collection.mutable.HashMap

import com.wordnik.swagger.client._
import scala.concurrent.Future
import collection.mutable

import java.net.URI

import com.wordnik.swagger.client.ClientResponseReaders.Json4sFormatsReader._
import com.wordnik.swagger.client.RequestWriters.Json4sFormatsWriter._

import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent._
import scala.concurrent.duration._
import scala.util.{Failure, Success, Try}

import org.json4s._

class LineageRESTApi(
  val defBasePath: String = "https://localhost:21000",
  defApiInvoker: ApiInvoker = ApiInvoker
) {
  private lazy val dateTimeFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  private val dateFormatter = {
    val formatter = new SimpleDateFormat("yyyy-MM-dd")
    formatter.setTimeZone(TimeZone.getTimeZone("UTC"))
    formatter
  }
  implicit val formats = new org.json4s.DefaultFormats {
    override def dateFormatter = dateTimeFormatter
  }
  implicit val stringReader: ClientResponseReader[String] = ClientResponseReaders.StringReader
  implicit val unitReader: ClientResponseReader[Unit] = ClientResponseReaders.UnitReader
  implicit val jvalueReader: ClientResponseReader[JValue] = ClientResponseReaders.JValueReader
  implicit val jsonReader: ClientResponseReader[Nothing] = JsonFormatsReader
  implicit val stringWriter: RequestWriter[String] = RequestWriters.StringWriter
  implicit val jsonWriter: RequestWriter[Nothing] = JsonFormatsWriter

  var basePath: String = defBasePath
  var apiInvoker: ApiInvoker = defApiInvoker

  def addHeader(key: String, value: String): mutable.HashMap[String, String] = {
    apiInvoker.defaultHeaders += key -> value
  }

  val config: SwaggerConfig = SwaggerConfig.forUrl(new URI(defBasePath))
  val client = new RestClient(config)
  val helper = new LineageRESTApiAsyncHelper(client, config)

  /**
   * Returns lineage info about entity.
   * Returns lineage info about entity.
   *
   * @param guid - unique entity id 
   * @param depth - number of hops for lineage (optional, default to 3)
   * @param direction - input, output or both (optional, default to BOTH)
   * @return JsonAtlasLineageInfo
   */
  def getLineageGraph(guid: String, depth: Option[Integer] = Option(3), direction: Option[String] = Option("BOTH")): Option[JsonAtlasLineageInfo] = {
    val await = Try(Await.result(getLineageGraphAsync(guid, depth, direction), Duration.Inf))
    await match {
      case Success(i) => Some(await.get)
      case Failure(t) => None
    }
  }

  /**
   * Returns lineage info about entity. asynchronously
   * Returns lineage info about entity.
   *
   * @param guid - unique entity id 
   * @param depth - number of hops for lineage (optional, default to 3)
   * @param direction - input, output or both (optional, default to BOTH)
   * @return Future(JsonAtlasLineageInfo)
   */
  def getLineageGraphAsync(guid: String, depth: Option[Integer] = Option(3), direction: Option[String] = Option("BOTH")): Future[JsonAtlasLineageInfo] = {
      helper.getLineageGraph(guid, depth, direction)
  }

}

class LineageRESTApiAsyncHelper(client: TransportClient, config: SwaggerConfig) extends ApiClient(client, config) {

  def getLineageGraph(guid: String,
    depth: Option[Integer] = Option(3),
    direction: Option[String] = Option("BOTH")
    )(implicit reader: ClientResponseReader[JsonAtlasLineageInfo]): Future[JsonAtlasLineageInfo] = {
    // create path and map variables
    val path = (addFmt("/v2/lineage/{guid}")
      replaceAll("\\{" + "guid" + "\\}", guid.toString))

    // query params
    val queryParams = new mutable.HashMap[String, String]
    val headerParams = new mutable.HashMap[String, String]

    if (guid == null) throw new Exception("Missing required parameter 'guid' when calling LineageRESTApi->getLineageGraph")

    depth match {
      case Some(param) => queryParams += "depth" -> param.toString
      case _ => queryParams
    }
    direction match {
      case Some(param) => queryParams += "direction" -> param.toString
      case _ => queryParams
    }

    val resFuture = client.submit("GET", path, queryParams.toMap, headerParams.toMap, "")
    resFuture flatMap { resp =>
      process(reader.read(resp))
    }
  }


}
